rules:
  - type: RULE-SET
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    policy: REJECT-200
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/DouYin/DouYin.list
    prolicy: PROXY
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
    policy: PROXY
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
    policy: DIRECT
  - type: GEOIP
    country: PRIVATE
    policy: DIRECT
  - type: FINAL
    policy: PROXY
