rules:
  - type: RULE-SET
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    policy: REJECT-200
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/DouYin/DouYin.list
    policy: PROXY
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Telegram/Telegram.list
    policy: PROXY
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Proxy/Proxy.list
    policy: PROXY
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple.list
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple_Domain.list
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/WeChat/WeChat.list
    policy: DIRECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Direct/Direct.list
    policy: DIRECT
   - type: RULE-SET
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan.list
    policy: DIRECT
  - type: GEOIP
    country: PRIVATE
    policy: DIRECT
  - type: GEOIP
    country: CN
    policy: DIRECT
  - type: FINAL
    policy: PROXY
